trigger:
- master

pool:
  vmImage: "ubuntu-16.04"

variables:
  hugo.version: '0.55.6'
  blog.path: 'darylwalleck.dev'
  system.debug: true

steps:
- checkout: self
  submodules: 'true'

- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
  displayName: "Download Hugo"

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: "Install Hugo"

- script:
    hugo --log -v
  displayName: 'Generate Blog'

- task: CopyFiles@2
  displayName: 'Copy Blog'
  inputs:
    SourceFolder: './public'
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'
